-- MySQL Script generated by MySQL Workbench
-- Thu May 18 12:02:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fruta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fruta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruta` DEFAULT CHARACTER SET utf8 ;
USE `fruta` ;

-- -----------------------------------------------------
-- Table `fruta`.`fruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruta`.`fruta` ;

CREATE TABLE IF NOT EXISTS `fruta`.`fruta` (
  `idfruta` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidadQuilos` INT NOT NULL,
  PRIMARY KEY (`idfruta`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
